# Generated by Django 5.1.1 on 2024-09-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_seller_address_seller_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FRUITS', 'Fruits'), ('VEGETABLES', 'Vegetables'), ('DAIRY', 'Dairy Products'), ('MEAT', 'Meat & Poultry'), ('SEAFOOD', 'Seafood'), ('GRAINS', 'Grains & Cereals'), ('HERBS', 'Herbs & Spices'), ('BAKERY', 'Bakery & Pastries'), ('BEVERAGES', 'Beverages'), ('ORGANIC', 'Organic Products'), ('NUTS', 'Nuts & Seeds'), ('OILS', 'Oils & Vinegars'), ('JAMS', 'Jams & Preserves'), ('HONEY', 'Honey & Sweeteners'), ('DRIED', 'Dried Fruits'), ('FROZEN', 'Frozen Foods'), ('EGGS', 'Eggs'), ('CONDIMENTS', 'Condiments & Sauces'), ('SNACKS', 'Snacks & Confections'), ('TEA', 'Tea & Coffee'), ('HEALTH', 'Health & Wellness'), ('FLOWERS', 'Flowers & Plants')], default='FRUITS', max_length=20),
        ),
    ]
